import os
from dotenv import load_dotenv

load_dotenv()
# MONGODB
MONGODB_URL = os.environ.get("URL_MONGODB")
MONGODB_DB_ORAICHAIN = os.environ.get("DB_NAME_ORAICHAIN")


# DISCORD
DISCORD_URL_ERROR = os.getenv("DISCORD_WEBHOOK_URL_ERROR")
DISCORD_URL_SUCCESS = os.getenv("DISCORD_WEBHOOK_URL_SUCCESS")
DISCORD_PLUME_WEBHOOK_URL_ERROR = os.getenv("DISCORD_PLUME_WEBHOOK_URL_ERROR")
DISCORD_AGENT_MAX_WEBHOOK_URL_ERROR = os.getenv("DISCORD_AGENT_MAX_WEBHOOK_URL_ERROR")
DISCORD_LOGO_ERROR = os.getenv("DISCORD_LOGO_ERROR")
DISCORD_LOGO_SUCCESS = os.getenv("DISCORD_LOGO_SUCCESS")
DISCORD_SERVER_NAME = os.getenv("DISCORD_SERVER_NAME")
DISCORD_USER_NAME = "Data Lab Bot"
DISCORD_AVATAR_URL = "https://banner2.cleanpng.com/20180320/roe/kisspng-logo-big-data-organization-technology-network-symbol-5ab11337f3c8d1.2913317615215542319986.jpg"


# ENVIRONMENT
ENVIRONMENT = os.environ.get("ENVIRONMENT")


# PROXIES
PROXY_AUTH_USERNAME = os.getenv("PROXY_AUTH_USERNAME")
PROXY_AUTH_PASSWORD = os.getenv("PROXY_AUTH_PASSWORD")

# KAFKA
KAFKA_HOST = os.getenv("KAFKA_HOST")
KAFKA_PORT = os.getenv("KAFKA_PORT")
KAFKA_USERNAME = os.getenv("KAFKA_USERNAME")
KAFKA_PASSWORD = os.getenv("KAFKA_PASSWORD")

# MODESTUS
MONGO_MODESTUS_DB_NAME = "blog-data"

# NEW YORK TIME
NEW_YORK_TIME_TOKEN = os.getenv("NEW_YORK_TIME_TOKEN")

# TWITTER
TWITTER_AUTH_TOKEN = os.getenv("TWITTER_AUTH_TOKEN")
TWITTER_COOKIES_CRYPTO_COLLECTION_NAME = "twitter_cookies"
TWITTER_COOKIES_POLITICS_COLLECTION_NAME = "twitter_cookies_politics"
TWITTER_COOKIES_SEARCH_COLLECTION_NAME = "twitter_cookies"
TWITTER_COOKIES_MENTIONS_COLLECTION_NAME = "twitter_distilled"


# SPLASH
SPLASH_HOST = os.getenv("SPLASH_HOST")

# DISTILLED
MONGO_DISTILLED_DB_NAME = "distilled-ai"
COOKIE_TRADING_VIEW_COLLECTION = "trading_view_cookies"

# DISTILLED-AI
MONGO_DATA_DISTILLED_URI = os.getenv("MONGO_DATA_DISTILLED_URI")
MONGO_DATA_DISTILLED_DB_NAME = "distilled"
DISTILLED_TWITTER_COOKIES_COLLECTION_NAME = "distilled-twitter-cookies"
