# COINMARKETCAP TOP CRYPTO
TOP_50_CRYPTO_COINMARKETCAP = [
    {"id": 1, "name": "Bitcoin", "symbol": "BTC"},
    {"id": 1027, "name": "Ethereum", "symbol": "ETH"},
    {"id": 1839, "name": "BNB", "symbol": "BNB"},
    {"id": 5426, "name": "Solana", "symbol": "SOL"},
    {"id": 52, "name": "XRP", "symbol": "XRP"},
    {"id": 74, "name": "Dogecoin", "symbol": "DOGE"},
    {"id": 11419, "name": "Toncoin", "symbol": "TON"},
    {"id": 1958, "name": "TRON", "symbol": "TRX"},
    {"id": 2010, "name": "Cardano", "symbol": "ADA"},
    {"id": 5805, "name": "Avalanche", "symbol": "AVAX"},
    {"id": 5994, "name": "Shiba Inu", "symbol": "SHIB"},
    {"id": 1975, "name": "Chainlink", "symbol": "LINK"},
    {"id": 6636, "name": "Polkadot", "symbol": "DOT"},
    {"id": 4943, "name": "Dai", "symbol": "DAI"},
    {"id": 3957, "name": "UNUS SED LEO", "symbol": "LEO"},
    {"id": 6535, "name": "NEAR Protocol", "symbol": "NEAR"},
    {"id": 2, "name": "Litecoin", "symbol": "LTC"},
    {"id": 20396, "name": "Kaspa", "symbol": "KAS"},
    {"id": 7083, "name": "Uniswap", "symbol": "UNI"},
    {"id": 8916, "name": "Internet Computer", "symbol": "ICP"},
    {"id": 3773, "name": "Artificial Superintelligence Alliance", "symbol": "FET"},
    {"id": 20947, "name": "Sui", "symbol": "SUI"},
    {"id": 21794, "name": "Aptos", "symbol": "APT"},
    {"id": 24478, "name": "Pepe", "symbol": "PEPE"},
    {"id": 328, "name": "Monero", "symbol": "XMR"},
    {"id": 22974, "name": "Bittensor", "symbol": "TAO"},
    {"id": 28321, "name": "Matic", "symbol": "POL"},
    {"id": 512, "name": "Stellar", "symbol": "XLM"},
    {"id": 1321, "name": "Ethereum Classic", "symbol": "ETC"},
    {"id": 5690, "name": "Render", "symbol": "RENDER"},
    {"id": 4847, "name": "Stacks", "symbol": "STX"},
    {"id": 10603, "name": "Immutable", "symbol": "IMX"},
    {"id": 3897, "name": "OKB", "symbol": "OKB"},
    {"id": 7278, "name": "Aave", "symbol": "AAVE"},
    {"id": 3635, "name": "Cronos", "symbol": "CRO"},
    {"id": 2280, "name": "Filecoin", "symbol": "FIL"},
    {"id": 11841, "name": "Arbitrum", "symbol": "ARB"},
    {"id": 7226, "name": "Injective", "symbol": "INJ"},
    {"id": 27075, "name": "Mantle", "symbol": "MNT"},
    {"id": 11840, "name": "Optimism", "symbol": "OP"},
    {"id": 4642, "name": "Hedera", "symbol": "HBAR"},
    {"id": 3077, "name": "VeChain", "symbol": "VET"},
    {"id": 28752, "name": "dogwifhat", "symbol": "WIF"},
    {"id": 3513, "name": "Fantom", "symbol": "FTM"},
    {"id": 3794, "name": "Cosmos", "symbol": "ATOM"},
    {"id": 6719, "name": "The Graph", "symbol": "GRT"},
]